### ISSUE TITLE
Support the inclusion of commit/version of test in ImageStats

### ISSUE THREAD

**Issue by zakkak** [Karm/collector#22]
Currently [ImageStats](https://github.com/Karm/collector/blob/main/src/main/java/com/redhat/quarkus/mandrel/collector/report/model/ImageStats.java) only keep track of the GraalVM/Mandrel version (`generator_version`) used to generate them, but when it comes to the benchmark it only keeps it's name (`img_name`). 

That way when inspecting the data if we observe something that needs investigation there is no way to know which specific version of the benchmark was used. The best we can do now is to look for the commit hashes in the corresponding repository based on the timestamp.

[PerfStats](https://github.com/Karm/collector/blob/main/src/main/java/com/redhat/quarkus/mandrel/collector/report/model/perf/PerfStatStats.java) include this information under `quarkusVersion`.

I believe we should introduce a similar entry for ImageStats as well (`testVersion` ?).

This would allow us to have the Quarkus CI (which uses a fixed/stable Mandrel image in contrast to our CI) push stats to the collector with every run of the CI on the `main` branch (or even for each PR) enabling us to (more) easily trace the commits that caused some regression.  

cc @jerboaa

**Comment by jerboaa** [comment]
The point of ImageStats is to be a verbatim copy of the `build-output.json` files. Or at least it's supposed to be GraalVM/Mandrel specific. It's now lagging behind since that json output gained some more info since ImageStats got added. Nevertheless the way we feed this to the collector is here:
https://github.com/graalvm/mandrel/blob/82e6ba445d7c6dea8e4cdbdf2c8bf0ce8b527753/.github/import_stats.sh#L29-L41

So maybe we need some update for a specific `ImageStat` record to get a `test_version` added which would be amounting to the quarkus git sha retrieved elsewhere or something like that. It should be an optional field.
